Remove AWS_LAMBDA_FUNCTION_NAME from environment variables (AWS reserved)
AWS Lambda automatically provides AWS_LAMBDA_FUNCTION_NAME as a runtime
environment variable. Attempting to set it manually in Terraform causes:

  InvalidParameterValueException: Lambda was unable to configure your
  environment variables because the environment variables you have
  provided contains reserved keys that are currently not supported
  for modification. Reserved keys used in this request:
  AWS_LAMBDA_FUNCTION_NAME

Fix: Removed the manual setting. The Python code already reads this
variable with os.environ.get('AWS_LAMBDA_FUNCTION_NAME'), which will
get the AWS-provided value automatically at runtime.

AWS automatically sets these reserved variables:
- AWS_LAMBDA_FUNCTION_NAME
- AWS_LAMBDA_FUNCTION_VERSION
- AWS_LAMBDA_FUNCTION_MEMORY_SIZE
- AWS_LAMBDA_LOG_GROUP_NAME
- AWS_LAMBDA_LOG_STREAM_NAME
- And others

Reference: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html